import turtle
turtle.Screen().bgcolor("Orange")
sc=turtle.Screen()
sc.setup(400,300)
turtle.title("Welcome To Turtle Window")
turtle.pensize(10)
turtle.speed(4)
turtle.pencolor("White")
turtle.fillcolor("cyan")
turtle.begin_fill()
turtle.forward(100)
turtle.right(90)
turtle.forward(100)
turtle.right(90)
turtle.forward(100)
turtle.right(90)
turtle.forward(100)
turtle.right(90)
turtle.end_fill()
turtle.done()